<?php

$modversion['name']        = "BattleField 1942 Stats";
$modversion['version']     = 1.00;
$modversion['description'] = "BattleField 1942 Stats Logger";
$modversion['author']      = "by Widowmaker";
$modversion['credits']     = "Battlefield Server Manager and BFSM Log Parser";
$modversion['help']        = "docs/doc.php";
$modversion['license']     = "GPL see LICENSE";
$modversion['official']    = 0;
$modversion['image']       = "logo.gif";
$modversion['dirname']     = "bfstats";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "contactbook";
//$modversion['tables'][1] = "popsettings";

// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = "php/admin/index.php";
$modversion['adminmenu']  = "php/admin/menu.php";
// Menu
$modversion['hasMain'] = 1;

// block
/*$modversion['blocks'][1]['file'] = "blocks.php";
$modversion['blocks'][1]['name'] = "Gaming Servers";
$modversion['blocks'][1]['description'] = "Gaming Server Monitor";
$modversion['blocks'][1]['show_func'] = "show_servers";
*/
?>
